/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.InvoiceDetail;

import View.Invoice.*;
import Controller.ChiTietHoaDonController;
import Model.HoaDon;
import Model.ChiTietHoaDon;
import Model.SanPham;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Manh
 */
public class frmChiTietHoaDon extends javax.swing.JPanel {

    private boolean cothem = true;
    private final ChiTietHoaDonController chiTietHoaDonController = new ChiTietHoaDonController();
    private final DefaultTableModel tableModel = new DefaultTableModel();

    /**
     * Creates new form frmInvoice
     */
    public frmChiTietHoaDon() throws SQLException {
        initComponents();
        String[] colsName = {"Id", "Số Hóa Đơn", "Tên Sản Phẩm", "Số Lượng", "Đơn Giá", "Tổng Tiền"}; // Đặt tiêu đề cột cho tableModel
        tableModel.setColumnIdentifiers(colsName);
        tblChiTietHoaDon.setModel(tableModel); // Kết nối jtable với tableModel
        hienThiDuLieu();

    }

    public void hienThiDuLieu() throws SQLException {
        // Lấy danh sách hóa đơn từ cơ sở dữ liệu
        List<ChiTietHoaDon> danhSach = chiTietHoaDonController.getChiTietHoaDonById();
        try {
            // Xóa dữ liệu cũ trước khi thêm mới
            tableModel.setRowCount(0);

            // Duyệt qua từng dòng của danh sách
            for (ChiTietHoaDon item : danhSach) {
                // Tạo một mảng đối tượng cho mỗi dòng
                Object[] rows = {
                    item.getChiTietHoaDonID(),
                    item.getHoaDon().getSoHoaDon(),
                    item.getSanPham().getTenSanPham(),
                    item.getSoLuong(),
                    item.getDonGia(),
                    item.getThanhTien()
                };
                // Thêm dòng dữ liệu vào tableModel
                tableModel.addRow(rows);
            }
        } catch (Exception e) {
            // Xử lý các lỗi khác
            System.err.println("Đã có lỗi xảy ra: " + e.getMessage());
            e.printStackTrace();
        }
        // Xử lý lỗi SQL một cách chi tiết hơn

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChiTietHoaDon = new javax.swing.JTable();
        btnAddInvoice = new javax.swing.JButton();
        btnUpdateInvoice = new javax.swing.JButton();
        btnDeleteInvoice = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiemChiTietHoaDon = new javax.swing.JTextField();

        tblChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Số hóa đơn", "Sản phẩm", "Số lượng", "Giá bán", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblChiTietHoaDon);

        btnAddInvoice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/8666718_plus_circle_icon.png"))); // NOI18N
        btnAddInvoice.setText("Thêm");
        btnAddInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInvoiceActionPerformed(evt);
            }
        });

        btnUpdateInvoice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/8666806_edit_write_pen_icon (1).png"))); // NOI18N
        btnUpdateInvoice.setText("Sửa");
        btnUpdateInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateInvoiceActionPerformed(evt);
            }
        });

        btnDeleteInvoice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/8666597_trash_2_icon.png"))); // NOI18N
        btnDeleteInvoice.setText("Xóa");
        btnDeleteInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteInvoiceActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Search:");

        txtTimKiemChiTietHoaDon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemChiTietHoaDonKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtTimKiemChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(btnAddInvoice)
                .addGap(47, 47, 47)
                .addComponent(btnUpdateInvoice)
                .addGap(39, 39, 39)
                .addComponent(btnDeleteInvoice)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddInvoice)
                    .addComponent(btnUpdateInvoice)
                    .addComponent(btnDeleteInvoice)
                    .addComponent(jLabel1)
                    .addComponent(txtTimKiemChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInvoiceActionPerformed
        ThemChiTietHoaDon themChiTietHoaDon = new ThemChiTietHoaDon(this); // Truyền tham chiếu của frmInvoice
        themChiTietHoaDon.setVisible(true);
        
    }//GEN-LAST:event_btnAddInvoiceActionPerformed

    private void btnDeleteInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteInvoiceActionPerformed
        int row = this.tblChiTietHoaDon.getSelectedRow();
        int id = Integer.parseInt(this.tblChiTietHoaDon.getModel().getValueAt(row, 0).toString());
        try {
            if (id == 0) {
                JOptionPane.showMessageDialog(null, "Chon 1 loai SP de xoa", "Thong bao", 1);
            } else {
                if (JOptionPane.showConfirmDialog(null, "Ban muon xoa loai " + id + "nay hay khong ? ", "Thong bao", 2) == 0) {
                    chiTietHoaDonController.xoaHoaDon(id);//goi ham xoa du lieu theo ma loai
                    xoaDuLieu();//Xoa du lieu trong tableModel
                    hienThiDuLieu();//Do du lieu vao table Model

                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Xóa thất bại", "Thong bao", 1);
        }
    }//GEN-LAST:event_btnDeleteInvoiceActionPerformed

    private void btnUpdateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateInvoiceActionPerformed
        int selectedRow = tblChiTietHoaDon.getSelectedRow();

        // Kiểm tra xem đã chọn một hàng trong bảng chưa
        if (selectedRow >= 0) {
            try {
                // Lấy dữ liệu từ hàng đã chọn
                int cthdId = Integer.parseInt(tblChiTietHoaDon.getValueAt(selectedRow, 0).toString());
                String hdNumber = tblChiTietHoaDon.getValueAt(selectedRow, 1).toString();
                String sanPham = tblChiTietHoaDon.getValueAt(selectedRow, 2).toString();
                int soLuong = Integer.parseInt(tblChiTietHoaDon.getValueAt(selectedRow, 3).toString());
                // Chuyển đổi giá trị TotalAmount và TaxAmount từ String sang BigDecimal
                BigDecimal giaBan = new BigDecimal(tblChiTietHoaDon.getValueAt(selectedRow, 4).toString().replace(",", ""));
                BigDecimal thanhTien = new BigDecimal(tblChiTietHoaDon.getValueAt(selectedRow, 5).toString().replace(",", ""));

                // Mở form UpdateInvoice
                CapNhatChiTietHoaDon capNhatChiTietHoaDon = new CapNhatChiTietHoaDon(this, cthdId, hdNumber, sanPham, soLuong, giaBan, thanhTien);
                capNhatChiTietHoaDon.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Có lỗi xảy ra khi lấy dữ liệu: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một hóa đơn để cập nhật", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateInvoiceActionPerformed

    private void txtTimKiemChiTietHoaDonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemChiTietHoaDonKeyReleased
        String keyword = txtTimKiemChiTietHoaDon.getText();
        try {
            List<ChiTietHoaDon> lst;
            if (keyword.isEmpty()) {
                // Nếu ô tìm kiếm trống, hiển thị tất cả khách hàng
                lst = chiTietHoaDonController.getChiTietHoaDonById();
            } else {
                // Gọi phương thức tìm kiếm
                lst = chiTietHoaDonController.timKiemChiTietHoaDon(keyword);
            }

            // Cập nhật lại dữ liệu trong bảng
            xoaDuLieu(); // Xóa dữ liệu cũ trong tableModel
            for (ChiTietHoaDon item : lst) {
                Object[] rows = {item.getChiTietHoaDonID(),
                    item.getHoaDon().getSoHoaDon(),
                    item.getSanPham().getTenSanPham(),
                    item.getSoLuong(),
                    item.getDonGia(),
                    item.getThanhTien()};
                tableModel.addRow(rows); // Thêm dòng dữ liệu mới vào tableModel
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtTimKiemChiTietHoaDonKeyReleased

    public void xoaDuLieu() throws SQLException {
//Lay chi so dong cuoi cung
        int n = tableModel.getRowCount() - 1;
        for (int i = n; i >= 0; i--) {
            tableModel.removeRow(i);//Remove tung dong
        }
    }

    public void refreshData() throws SQLException {
        hienThiDuLieu(); // Gọi phương thức hiện tại để cập nhật dữ liệu
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddInvoice;
    private javax.swing.JButton btnDeleteInvoice;
    private javax.swing.JButton btnUpdateInvoice;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblChiTietHoaDon;
    private javax.swing.JTextField txtTimKiemChiTietHoaDon;
    // End of variables declaration//GEN-END:variables
}
