/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.InvoiceDetail;

import Controller.ChiTietHoaDonController;
import Model.ChiTietHoaDon;
import Model.HoaDon;
import Model.SanPham;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manh
 */
public class ThemChiTietHoaDon extends javax.swing.JFrame {

    private final ChiTietHoaDonController ivdt = new ChiTietHoaDonController();
    private boolean cothem = true;
    private final DefaultTableModel tableModel = new DefaultTableModel();
    private frmChiTietHoaDon form;

    /**
     * Creates new form AddInvoice
     */
    public ThemChiTietHoaDon(frmChiTietHoaDon form) {
        initComponents();
        this.form = form; // Lưu tham chiếu của frmInvoice
        setLocationRelativeTo(null);
        hienThiDuLieuSanPhamCombo();
        hienThiDuLieuSoHoaDonCombo();
        cbbSanPham.addActionListener(e -> capNhatGiaBanTheoSanPham());
        capNhatGiaBanTheoSanPham();
    }

    final void hienThiDuLieuSanPhamCombo() {
        ResultSet result = null;
        try {
            result = ivdt.hienThiChiTietSanPham();
            while (result.next()) {
                cbbSanPham.addItem(result.getString("TenSanPham"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    final void hienThiDuLieuSoHoaDonCombo() {
        ResultSet result = null;
        try {
            result = ivdt.hienThiChiTietHoaDon();
            while (result.next()) {
                cbbSoHoaDon.addItem(result.getString("SoHoaDon"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void capNhatGiaBanTheoSanPham() {
        try {
            // Lấy tên sản phẩm từ ComboBox
            String tenSanPham = (String) cbbSanPham.getSelectedItem();

            // Kiểm tra nếu tên sản phẩm không null
            if (tenSanPham != null && !tenSanPham.isEmpty()) {
                // Gọi controller để lấy giá bán
                BigDecimal giaBan = ivdt.getGiaBanByTenSanPham(tenSanPham);

                // Hiển thị giá bán lên txtGiaBan
                txtGiaBan.setText(giaBan.toString());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi lấy giá bán sản phẩm!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSaveInvoiceDetail = new javax.swing.JButton();
        cbbSanPham = new javax.swing.JComboBox<>();
        txtGiaBan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbbSoHoaDon = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Thêm chi tiết hóa đơn");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Số hóa đơn:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Sản phẩm");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Quantity:");

        btnSaveInvoiceDetail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSaveInvoiceDetail.setText("Lưu");
        btnSaveInvoiceDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveInvoiceDetailActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Giá bán:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSaveInvoiceDetail)
                        .addGap(310, 310, 310))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(258, 258, 258))))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(cbbSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbSoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(txtGiaBan))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(16, 16, 16)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)
                        .addComponent(cbbSoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbbSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(btnSaveInvoiceDetail)
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveInvoiceDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveInvoiceDetailActionPerformed
        try {
            String soHoaDon = cbbSoHoaDon.getSelectedItem().toString();
            String tenSanPham = cbbSanPham.getSelectedItem().toString();
            int soLuong = Integer.parseInt(txtSoLuong.getText().trim());
            BigDecimal giaBan = new BigDecimal(txtGiaBan.getText());

            int sanPhamId = ivdt.getSanPhamIdByName(tenSanPham);
            int hoaDonId = ivdt.getHoaDonIdByName(soHoaDon);
            // Kiểm tra thông tin nhập vào
            if (soHoaDon == null || tenSanPham == null || sanPhamId == -1 || soLuong == -1) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Tạo đối tượng Invoice
            ChiTietHoaDon obj = new ChiTietHoaDon();

            HoaDon hoaDon = new HoaDon();
            hoaDon.setHoaDonId(hoaDonId);
            obj.setHoaDon(hoaDon);

            SanPham sanPham = new SanPham();
            sanPham.setSanPhamId(sanPhamId);
            obj.setSanPham(sanPham); // Sử dụng CustomerID

            obj.setSoLuong(soLuong);
            obj.setDonGia(giaBan);
            ivdt.themChiTietHoaDon(obj); // Thêm hóa đơn vào cơ sở dữ liệu

            // Gọi phương thức cập nhật dữ liệu trong frmInvoice
            if (this.form != null) {
                this.form.refreshData(); // Cập nhật dữ liệu bảng
            }

            JOptionPane.showMessageDialog(this, "Thêm hóa đơn thành công");
            dispose(); // Đóng cửa sổ AddInvoice
        } catch (SQLException ex) {
            Logger.getLogger(ThemChiTietHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveInvoiceDetailActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveInvoiceDetail;
    private javax.swing.JComboBox<String> cbbSanPham;
    private javax.swing.JComboBox<String> cbbSoHoaDon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
