/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Invoice;

import Controller.HoaDonController;
import Model.HoaDon;
import Model.KhachHang;
import com.toedter.calendar.JDateChooser;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manh
 */
public class CapNhatHoaDon extends javax.swing.JFrame {

    private final HoaDonController iv = new HoaDonController();
    private boolean cothem = true;
    private final DefaultTableModel tableModel = new DefaultTableModel();
    private frmHoaDon form;

    /**
     * Creates new form AddInvoice
     */
    public CapNhatHoaDon(frmHoaDon form, int hoaDonId, String soHoaDon, String tenKhachHang,
            BigDecimal tongTien, BigDecimal thueTien, Date ngayLapHoaDon,
            Date ngayHanThanhToan, String trangThai) {
        this.form = form;
        initComponents();
        setLocationRelativeTo(null);

        // Hiển thị danh sách khách hàng
        hienThiDuLieuKhachHangCombo();
        hienThiDuLieuTrangThaiCombo();

        // Hiển thị HoaDonID và Số Hóa Đơn
        txtHoaDonID.setText(String.valueOf(hoaDonId));
        txtSoHoaDon.setText(soHoaDon);

        // Set giá trị cho ComboBox Khách Hàng
        if (tenKhachHang != null) {
            cbbKhachHang.setSelectedItem(tenKhachHang);
        }

        // Định dạng số tiền
        DecimalFormat df = new DecimalFormat("#,###.00");

        // Hiển thị Tổng Tiền
        txtTongTien.setText(df.format(tongTien));

        // Hiển thị Tiền Thuế
        txtThueTien.setText(df.format(thueTien));

        // Hiển thị Ngày Lập Hóa Đơn và Ngày Hạn Thanh Toán
        NgayLapHoaDon.setDate(ngayLapHoaDon);  // Sử dụng `NgayLapHoaDon` đã tạo từ NetBeans
        NgayHanThanhToan.setDate(ngayHanThanhToan);  // Sử dụng `NgayHanThanhToan` đã tạo từ NetBeans

        // Set Trạng Thái
        if (trangThai != null) {
            cbbTrangThai.setSelectedItem(trangThai);
        }
    }

    final void hienThiDuLieuKhachHangCombo() {
        ResultSet result = null;
        try {
            result = iv.hienThiHoaDonKhachHang();
            while (result.next()) {
                cbbKhachHang.addItem(result.getString("TenKhachHang"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    final void hienThiDuLieuTrangThaiCombo() {
        ResultSet result = null;
        try {
            result = iv.hienThiHoaDonStatus();
            while (result.next()) {
                cbbTrangThai.addItem(result.getString("TrangThai"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSoHoaDon = new javax.swing.JTextField();
        txtTongTien = new javax.swing.JTextField();
        txtThueTien = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSaveInvoice = new javax.swing.JButton();
        cbbTrangThai = new javax.swing.JComboBox<>();
        cbbKhachHang = new javax.swing.JComboBox<>();
        NgayHanThanhToan = new com.toedter.calendar.JDateChooser();
        NgayLapHoaDon = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtHoaDonID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Add Invoice");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Invoice Number:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Customer:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Status:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Due Date:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Total Amount:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tax Amount:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Invoice Date:");

        btnSaveInvoice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSaveInvoice.setText("Save");
        btnSaveInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveInvoiceActionPerformed(evt);
            }
        });

        cbbTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTrangThaiActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Invoice ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSaveInvoice)
                        .addGap(323, 323, 323))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(302, 302, 302))))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(txtSoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(cbbKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(NgayHanThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(NgayLapHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThueTien, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(cbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHoaDonID, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHoaDonID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(10, 10, 10)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)
                        .addComponent(txtSoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtThueTien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(btnSaveInvoice))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NgayHanThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel4))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(NgayLapHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(cbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(118, 118, 118))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbbKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel8)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveInvoiceActionPerformed
        try {
            // Lấy thông tin từ các trường nhập liệu
            String soHoaDon = txtSoHoaDon.getText().trim();
            String tenKhachHang = cbbKhachHang.getSelectedItem() != null ? cbbKhachHang.getSelectedItem().toString() : "";

            // Lấy KhachHangID từ tên khách hàng
            int khachHangId = iv.getKhachHangIdByName(tenKhachHang);

            // Kiểm tra thông tin nhập vào
            if (soHoaDon.isEmpty() || tenKhachHang.isEmpty() || khachHangId == -1
                    || txtTongTien.getText().trim().isEmpty() || txtThueTien.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Kiểm tra chuyển đổi sang BigDecimal
//            BigDecimal tongTien, thueTien;
//            try {
//                tongTien = new BigDecimal(txtTongTien.getText().trim());
//                // Nếu muốn sử dụng thueTien, bỏ chú thích dòng dưới đây
//                // thueTien = new BigDecimal(txtThueTien.getText().trim());
//            } catch (NumberFormatException ex) {
//                JOptionPane.showMessageDialog(this, "Số tiền phải là giá trị số", "Thông báo", JOptionPane.WARNING_MESSAGE);
//                return;
//            }

            // Lấy giá trị trạng thái từ ComboBox
            String trangThai = cbbTrangThai.getSelectedItem() != null ? cbbTrangThai.getSelectedItem().toString() : "Chưa thanh toán"; // Giá trị mặc định

            // Lấy ngày lập hóa đơn và ngày hạn thanh toán
            Date ngayLapHoaDon = (Date) NgayLapHoaDon.getDate();
            Date ngayHanThanhToan = (Date) NgayHanThanhToan.getDate();

            // Kiểm tra ngày lập hóa đơn và ngày hạn thanh toán
            if (ngayLapHoaDon == null || ngayHanThanhToan == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày hợp lệ", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (ngayHanThanhToan.before(ngayLapHoaDon)) {
                JOptionPane.showMessageDialog(this, "Ngày đến hạn không thể trước ngày lập hóa đơn", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Tạo đối tượng HoaDon và gán giá trị
            HoaDon obj = new HoaDon();
            obj.setHoaDonId(Integer.parseInt(txtHoaDonID.getText()));
            obj.setSoHoaDon(soHoaDon);
            
            KhachHang khachHang = new KhachHang();
            khachHang.setKhachHangId(khachHangId);
            obj.setKhachHang(khachHang);
            
//            obj.setTongTien(tongTien);
            // obj.setThueTien(thueTien); // Nếu cần, có thể bỏ chú thích dòng này
            obj.setNgayLapHoaDon(ngayLapHoaDon);
            obj.setNgayHanThanhToan(ngayHanThanhToan);
            obj.setTrangThai(trangThai);

            // Thực hiện sửa hóa đơn
            iv.suaHoaDon(obj);

            // Hiển thị dữ liệu lên form
            if (this.form == null) {
                this.form = new frmHoaDon();
            }
            this.form.hienThiDuLieu();

            // Thông báo sửa hóa đơn thành công
            JOptionPane.showMessageDialog(this, "Sửa hóa đơn thành công");
            dispose(); // Đóng form sửa hóa đơn
        } catch (SQLException ex) {
            Logger.getLogger(CapNhatHoaDon.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Lỗi khi sửa hóa đơn: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSaveInvoiceActionPerformed

    private void cbbTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTrangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTrangThaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser NgayHanThanhToan;
    private com.toedter.calendar.JDateChooser NgayLapHoaDon;
    private javax.swing.JButton btnSaveInvoice;
    private javax.swing.JComboBox<String> cbbKhachHang;
    private javax.swing.JComboBox<String> cbbTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtHoaDonID;
    private javax.swing.JTextField txtSoHoaDon;
    private javax.swing.JTextField txtThueTien;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
