/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Invoice;

import Controller.InvoiceController;
import Model.Invoice;
import Model.Product;
import View.Invoice.AddInvoice;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Manh
 */
public class frmInvoice extends javax.swing.JPanel {

    private boolean cothem = true;
    private final InvoiceController iv = new InvoiceController();
    private final DefaultTableModel tableModel = new DefaultTableModel();

    /**
     * Creates new form frmInvoice
     */
    public frmInvoice() throws SQLException {
        initComponents();
        String[] colsName = {"Id", "Name Number", "Name Customer", "Total Amount", "Tax Amount", "Invoice Date", "DueDate", "Status"}; // Đặt tiêu đề cột cho tableModel
        tableModel.setColumnIdentifiers(colsName);
        tblInvoice.setModel(tableModel); // Kết nối jtable với tableModel
        ShowData();

    }

    public void ShowData() throws SQLException {
        List<Invoice> lst = iv.getInvoiceById(); // Lấy danh sách loại sản phẩm từ cơ sở dữ liệu
        try {
            // Xóa dữ liệu cũ trước khi thêm mới
            tableModel.setRowCount(0);
            for (Invoice item : lst) { // Duyệt qua từng dòng của lst
                Object[] rows = {item.getIvId(), item.getIvNumber(), item.getCusName(), item.getTotalAmount(), item.getTaxAmount(), item.getIvDate(), item.getDueDate(), item.getStatus()};
                // Giả sử các phương thức getId, getTenLoai, getMoTa đã được định nghĩa trong lớp LoaiSP
                tableModel.addRow(rows); // Đưa dòng dữ liệu vào tableModel
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInvoice = new javax.swing.JTable();
        btnAddInvoice = new javax.swing.JButton();
        btnUpdateInvoice = new javax.swing.JButton();
        btnDeleteInvoice = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSearchInvoice = new javax.swing.JTextField();

        tblInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Invoice Number", "Customer Name", "Total Amount", "TaxAmount", "InvoiceDate", "DueDate", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInvoice);

        btnAddInvoice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddInvoice.setText("Add");
        btnAddInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInvoiceActionPerformed(evt);
            }
        });

        btnUpdateInvoice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateInvoice.setText("Update");
        btnUpdateInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateInvoiceActionPerformed(evt);
            }
        });

        btnDeleteInvoice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteInvoice.setText("Delete");
        btnDeleteInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteInvoiceActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Search:");

        txtSearchInvoice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchInvoiceKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtSearchInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(btnAddInvoice)
                .addGap(47, 47, 47)
                .addComponent(btnUpdateInvoice)
                .addGap(39, 39, 39)
                .addComponent(btnDeleteInvoice)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddInvoice)
                    .addComponent(btnUpdateInvoice)
                    .addComponent(btnDeleteInvoice)
                    .addComponent(jLabel1)
                    .addComponent(txtSearchInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInvoiceActionPerformed
        AddInvoice addinvoice = new AddInvoice(this); // Truyền tham chiếu của frmInvoice
        addinvoice.setVisible(true);
    }//GEN-LAST:event_btnAddInvoiceActionPerformed

    private void btnDeleteInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteInvoiceActionPerformed
        int row = this.tblInvoice.getSelectedRow();
        int id = Integer.parseInt(this.tblInvoice.getModel().getValueAt(row, 0).toString());
        try {
            if (id == 0) {
                JOptionPane.showMessageDialog(null, "Chon 1 loai SP de xoa", "Thong bao", 1);
            } else {
                if (JOptionPane.showConfirmDialog(null, "Ban muon xoa loai " + id + "nay hay khong ? ", "Thong bao", 2) == 0) {
                    iv.DeleteData(id);//goi ham xoa du lieu theo ma loai
                    ClearData();//Xoa du lieu trong tableModel
                    ShowData();//Do du lieu vao table Model

                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Xóa thất bại", "Thong bao", 1);
        }
    }//GEN-LAST:event_btnDeleteInvoiceActionPerformed

    private void btnUpdateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateInvoiceActionPerformed
        int selectedRow = tblInvoice.getSelectedRow();

        // Kiểm tra xem đã chọn một hàng trong bảng chưa
        if (selectedRow >= 0) {
            try {
                // Lấy dữ liệu từ hàng đã chọn
                int ivid = Integer.parseInt(tblInvoice.getValueAt(selectedRow, 0).toString());
                String ivnumber = tblInvoice.getValueAt(selectedRow, 1).toString();
                String cusname = tblInvoice.getValueAt(selectedRow, 2).toString();

                // Chuyển đổi giá trị TotalAmount và TaxAmount từ String sang BigDecimal
                BigDecimal totalamount = new BigDecimal(tblInvoice.getValueAt(selectedRow, 3).toString().replace(",", ""));
                BigDecimal taxamount = new BigDecimal(tblInvoice.getValueAt(selectedRow, 4).toString().replace(",", ""));

                // Chuyển đổi Invoice Date và Due Date từ String hoặc sql.Date sang java.util.Date
                Date ivDate = new java.util.Date(((java.sql.Date) tblInvoice.getValueAt(selectedRow, 5)).getTime());
                Date dueDate = new java.util.Date(((java.sql.Date) tblInvoice.getValueAt(selectedRow, 6)).getTime());

                String status = tblInvoice.getValueAt(selectedRow, 7).toString();

                // Mở form UpdateInvoice
                UpdateInvoice updateInvoice = new UpdateInvoice(this, ivid, ivnumber, cusname, totalamount, taxamount, ivDate, dueDate, status);
                updateInvoice.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Có lỗi xảy ra khi lấy dữ liệu: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một hóa đơn để cập nhật", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateInvoiceActionPerformed

    private void txtSearchInvoiceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchInvoiceKeyReleased
        String keyword = txtSearchInvoice.getText();
        try {
            List<Invoice> lst;
            if (keyword.isEmpty()) {
                // Nếu ô tìm kiếm trống, hiển thị tất cả khách hàng
                lst = iv.getInvoiceById();
            } else {
                // Gọi phương thức tìm kiếm
                lst = iv.searchInvoice(keyword);
            }

            // Cập nhật lại dữ liệu trong bảng
            ClearData(); // Xóa dữ liệu cũ trong tableModel
            for (Invoice item : lst) {
                Object[] rows = {item.getIvId(), item.getIvNumber(), item.getCusName(), item.getTotalAmount(), item.getTaxAmount(), item.getIvDate(), item.getDueDate(), item.getStatus()};
                tableModel.addRow(rows); // Thêm dòng dữ liệu mới vào tableModel
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtSearchInvoiceKeyReleased

    public void ClearData() throws SQLException {
//Lay chi so dong cuoi cung
        int n = tableModel.getRowCount() - 1;
        for (int i = n; i >= 0; i--) {
            tableModel.removeRow(i);//Remove tung dong
        }
    }

    public void refreshData() throws SQLException {
        ShowData(); // Gọi phương thức hiện tại để cập nhật dữ liệu
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddInvoice;
    private javax.swing.JButton btnDeleteInvoice;
    private javax.swing.JButton btnUpdateInvoice;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInvoice;
    private javax.swing.JTextField txtSearchInvoice;
    // End of variables declaration//GEN-END:variables
}
