/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import View.Invoice.LuuTruHoaDon;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import View.Invoice.frmHoaDon;
//import View.InvoiceDetail.frmChiTietHoaDon;

/**
 *
 * @author Manh
 */
public class Home extends javax.swing.JFrame {

    JpanelLoader jpload = new JpanelLoader();
    private javax.swing.JPanel originalPanel;

    /**
     * Creates new form Home
     */
    public Home() {
        try {
            initComponents();
//        this.setExtendedState(Home.MAXIMIZED_BOTH);
            setLocationRelativeTo(null);
            frmTrangChu tc = new frmTrangChu();
            jpload.jPanelLoader(panel_load, tc);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnCustomers = new javax.swing.JToggleButton();
        Product = new javax.swing.JToggleButton();
        btnInvoiceDetail = new javax.swing.JToggleButton();
        btnUsers = new javax.swing.JToggleButton();
        btnReport = new javax.swing.JToggleButton();
        btnInvoice = new javax.swing.JToggleButton();
        btnTrangChu = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panel_load = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(btnCustomers);
        btnCustomers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCustomers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/8666755_users_group_icon_mini.png"))); // NOI18N
        btnCustomers.setText("Khách hàng");
        btnCustomers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomersActionPerformed(evt);
            }
        });
        jPanel1.add(btnCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 132, -1));

        buttonGroup1.add(Product);
        Product.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/8666784_box_package_delivery_icon.png"))); // NOI18N
        Product.setText("Sản phẩm");
        Product.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductActionPerformed(evt);
            }
        });
        jPanel1.add(Product, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 132, -1));

        buttonGroup1.add(btnInvoiceDetail);
        btnInvoiceDetail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInvoiceDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/8666675_clipboard_icon.png"))); // NOI18N
        btnInvoiceDetail.setText("In hóa đon");
        btnInvoiceDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceDetailActionPerformed(evt);
            }
        });
        jPanel1.add(btnInvoiceDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 132, -1));

        buttonGroup1.add(btnUsers);
        btnUsers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/8666609_user_icon.png"))); // NOI18N
        btnUsers.setText("Người dùng");
        btnUsers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 132, -1));

        buttonGroup1.add(btnReport);
        btnReport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReport.setText("Gửi Mail");
        jPanel1.add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 132, -1));

        buttonGroup1.add(btnInvoice);
        btnInvoice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/8666689_file_text_icon_mini.png"))); // NOI18N
        btnInvoice.setText("Hóa đơn");
        btnInvoice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceActionPerformed(evt);
            }
        });
        jPanel1.add(btnInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 132, -1));

        buttonGroup1.add(btnTrangChu);
        btnTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/8666691_home_icon.png"))); // NOI18N
        btnTrangChu.setText("Trang chủ");
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });
        jPanel1.add(btnTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 132, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/8666609_user_icon_max.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 32, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Admin");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 102, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pexels-pixelcop-2680270 (1).jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 190, 480));

        panel_load.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_loadLayout = new javax.swing.GroupLayout(panel_load);
        panel_load.setLayout(panel_loadLayout);
        panel_loadLayout.setHorizontalGroup(
            panel_loadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        panel_loadLayout.setVerticalGroup(
            panel_loadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_load, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_load, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersActionPerformed
        try {
            frmKhachHang cus = new frmKhachHang();
            System.out.println("Loading frmCustomer...");
            jpload.jPanelLoader(panel_load, cus);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnCustomersActionPerformed

    private void ProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductActionPerformed
        try {
            frmSanPham prd = new frmSanPham();
            jpload.jPanelLoader(panel_load, prd);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ProductActionPerformed

    private void btnInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceActionPerformed
        try {
            frmHoaDon iv = new frmHoaDon();
            jpload.jPanelLoader(panel_load, iv);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInvoiceActionPerformed

    private void btnInvoiceDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceDetailActionPerformed
        try {
            LuuTruHoaDon lthd = new LuuTruHoaDon();
            jpload.jPanelLoader(panel_load, lthd);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInvoiceDetailActionPerformed

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        frmUser nd = new frmUser();
        jpload.jPanelLoader(panel_load, nd);
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        try {
            frmTrangChu tc = new frmTrangChu();
            jpload.jPanelLoader(panel_load, tc);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTrangChuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Product;
    private javax.swing.JToggleButton btnCustomers;
    private javax.swing.JToggleButton btnInvoice;
    private javax.swing.JToggleButton btnInvoiceDetail;
    private javax.swing.JToggleButton btnReport;
    private javax.swing.JToggleButton btnTrangChu;
    private javax.swing.JToggleButton btnUsers;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_load;
    // End of variables declaration//GEN-END:variables
}
